version: '3.4'

services:
    api:
        restart: on-failure
        build: 
            context: .
            dockerfile: 'PaymentGateway/Dockerfile'
        depends_on:
            - bankmock
        ports:
            - "8085:80"
            - "4431:443"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/PaymentGateway.pfx
            - Kestrel__Certificates__Default__Password=password
        volumes: 
            - C:\temp\:/app/Infrastructure/Certificate
    bankmock:
        image: rodolpheche/wiremock:latest
        container_name: wiremock-standalone
        ports:
            - "8181:8080"
        expose:
            - 8080
        volumes: 
            - "./wiremock:/home/wiremock"
        command:
            - -verbose
            - -global-response-templating