version: '3.4'
services:
    api:
        restart: on-failure
        build: 
            context: .
            dockerfile: 'PaymentGateway/Dockerfile'
        depends_on:
            - bankmock
        ports:
            - "8085:80"
            - "4431:443"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80 
        volumes: 
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    bankmock:
        image: rodolpheche/wiremock
        container_name: wiremock-standalone
        expose:
            - 8080
        volumes: 
            - "./deploy/wiremock:/home/wiremock"
        command:
            - -verbose
            - -global-response-templating
            