FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
COPY . ./
RUN dotnet build "PaymentGateway/PaymentGateway.csproj" -c Release -o /app/build

# copy csproj and restore as distinct layers
COPY *.sln .
COPY *.csproj ./
RUN dotnet restore

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS publish
COPY . ./
RUN dotnet publish "PaymentGateway/PaymentGateway.csproj" -c Release -o /app/publish

# final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PaymentGateway.dll"]